FROM alpine:latest

ARG TARGETPLATFORM
ENV LANG=en_US.utf8
ENV TZ=Europe/Berlin

RUN apk update && \
    apk add musl-locales tzdata && \
    apk add \
    git \
    gcc \
    meson \
    bash \
    linux-headers \
    musl-dev \
    perl \
    ca-certificates \
    cmake \
    make \
    pkgconf \
    curl-dev \
    libarchive-dev \
    python3 \
    py3-yaml \
    && apk cache clean && \
    rm -rf /var/cache/apk/* /tmp/* /var/tmp/*


WORKDIR /build