FROM fedora:43

ARG TARGETPLATFORM
ENV LANG=en_US.utf8
ENV TZ=Europe/Berlin

RUN dnf update -y && \
    dnf install -y glibc-langpack-en tzdata && \
    dnf install -y \
    clang \
    gcc \
    gcc-c++ \
    git \
    meson \
    pkg-config \
    swig \
    valgrind \
    python3 \
    python3-devel \
    python3-pip \
    && dnf clean all && \
    rm -rf /var/cache/dnf/* /tmp/* /var/tmp/*

WORKDIR /build