FROM {{ base_image }}

ARG TARGETPLATFORM
ARG DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.utf8
ENV TZ=Europe/Berlin

RUN apt-get update && \
    apt-get install -y locales tzdata && \
    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 && \
    apt-get install --no-install-recommends -y \
{% for pkg in packages %}
    {{ pkg }} \
{% endfor %}
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

{% if "muon" in features %}
COPY --chmod=755 bin/samu bin/muon /usr/bin
{% endif %}

WORKDIR /build
