FROM {{ base_image }}

ARG TARGETPLATFORM
ENV LANG=en_US.utf8
ENV TZ=Europe/Berlin

RUN dnf update -y && \
    dnf install -y glibc-langpack-en tzdata && \
    dnf install -y \
{% for pkg in packages %}
    {{ pkg }} \
{% endfor %}
    && dnf clean all && \
    rm -rf /var/cache/dnf/* /tmp/* /var/tmp/*

{% if "muon" in features %}
COPY --chmod=755 bin/samu bin/muon /usr/bin
{% endif %}

WORKDIR /build
