# SPDX-License-Identifier: GPL-2.0
FROM {{ base_image }}

ARG TARGETPLATFORM
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV TZ=Europe/Berlin

RUN zypper --non-interactive refresh && \
    zypper --non-interactive install --no-recommends \
        glibc-locale-base \
        timezone && \
    zypper --non-interactive install --no-recommends \
{% for pkg in packages %}
    {{ pkg }} \
{% endfor %}
    && zypper clean --all && \
    rm -rf /var/cache/zypp/* /tmp/* /var/tmp/*

{% if "muon" in features %}
COPY --chmod=755 bin/samu bin/muon /usr/bin
{% endif %}

WORKDIR /build
