# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (c) 2026 Western Digital Corporation or its affiliates.
#
# Author: Dennis Maisenbacher <dennis.maisenbacher@wdc.com>
#
# A containerDisk is just the VM disk in /disk, owned by UID 107 (qemu). The
# build context is the directory holding the customized qcow2 ({{ variant }}/build).
FROM scratch
COPY --chown=107:107 {{ distro }}-{{ variant }}.qcow2 /disk/{{ distro }}-{{ variant }}.qcow2
