---
name: "🏗 Next"

on:
  push:
    branch:
      - master
  pull_request:

jobs:
  build_staging:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type:
          - debian
    name: Build staging container
    outputs:
      built_types: ${{ steps.set_output.outputs.types }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.12.0

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build staging image
        uses: docker/build-push-action@v6.19.2
        with:
          file: staging/Dockerfile.${{ matrix.type }}.staging
          platforms: linux/amd64
          push: true
          provenance: false
          tags: ghcr.io/linux-nvme/${{ matrix.type }}.staging:next

      - name: Set job output
        id: set_output
        run: |
          echo "types=[\"${{ matrix.type }}\"]" >> $GITHUB_OUTPUT

  build_tools:
    runs-on: ubuntu-latest
    needs: build_staging
    strategy:
      matrix:
        type: ${{ fromJSON(needs.build_staging.outputs.built_types) }}
    name: Build samurai and muon
    container:
      image: ghcr.io/linux-nvme/${{ matrix.type }}.staging:next
    steps:
      - uses: actions/checkout@v6

      - name: Build
        run: scripts/build-muon.sh

      - uses: actions/upload-artifact@v7
        name: Upload artifacts
        with:
          name: samu-muon-${{ matrix.type }}
          path: bin

  deploy_containers:
    runs-on: ubuntu-latest
    needs: build_tools
    strategy:
      matrix:
        type: ${{ fromJSON(needs.build_tools.outputs.all_types) }}
    name: Deploy final containers
    steps:
      - name: Check out repo
        uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: samu-muon-${{ matrix.type }}
          path: bin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.12.0

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build final image
        uses: docker/build-push-action@v6.19.2
        with:
          context: .
          file: Dockerfile.${{ matrix.type }}
          platforms: linux/amd64
          push: true
          provenance: false
          tags: ghcr.io/linux-nvme/${{ matrix.type }}:next

  deploy_cross_containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - armhf
          - ppc64le
          - s390x
    name: ubuntu cross container
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.12.0
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v6.19.2
        with:
          file: Dockerfile.ubuntu.${{ matrix.arch }}
          platforms: linux/amd64
          push: true
          provenance: false
          tags: |
            ghcr.io/linux-nvme/ubuntu-cross-${{ matrix.arch }}:next
